cc_test(
  name = "tests",
  srcs = ["BinFileTest.cpp"],
  deps = [
          "//tdlbcpp/src/Params:params",
          "//tdlbcpp/src:computeUnit",
          "@googletest//:gtest_main"
  ],
  copts = ["-Itdlbcpp/src"]
)



